AllCops:
  NewCops: enable
  inherit_mode: merge
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'test/**/*'
    - 'config/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb' 
